# action.yml
name: "Verify NPM files action"
description: "A Github Action that verifies all files referenced by the package.json file are present in the package tarball."
inputs:
  keys:
    description: |
      New line deliminated list of package.json keys to verify.
    required: false
    default: |
      main      
runs:
  using: 'node12'
  main: 'dist/index.js'
